theme: jekyll-theme-minimal
title: Camilo Granados
logo: /files/ProfPic3.jpeg
description: Ph.D. Candidate in Economics <br> University of Washington <br> <font size="2"> email: jcgc  uw.edu </font> <br> jcgc [at] uw.edu <p><a href="files/GranadosJC_resume.pdf">Curriculum Vitae</a></p>
