title: Camilo Granados
#logo: <img src="/files/logoEmpty.png" alt="" style="height: 120px; width:100px;"/> 
logo: files/UTDmono_EPPS_header_black.jpg
#header_EPPS_Black.png
#navbar_logo: files/logoEmpty.png
description: <br> <font size="2"> Assistant Professor of Economics <br> University of Texas at Dallas  </font> <br> <font size="2"> Email 1 &#58  <a href="mailto:camilo.granados@utdallas.edu">camilo.granados@utdallas.edu</a> <br> Email 2 &#58  <a href="mailto:cagranados8@gmail.com">cagranados8@gmail.com</a> </font>
#description: <font size="2"> Ph.D. in Economics <br> University of Washington (UW) </font> <br> <font size="1"> Email 1 &#58  <a href="mailto:jcgc@uw.edu">cagranados8 [at] gmail.com</a> <br> Email 2 &#58  <a href="mailto:jcgc@uw.edu">jcgc [at] uw.edu</a> </font> <p> <h4><a href="./Granados_CV.pdf"> Curriculum Vitae </a></h4></p> <p> <h4><a href="https://cagranados.github.io/research.html">Research</a></h4></p> <p><h4><a href="./teaching.html">Teaching</a></h4></p> <p><h4><a href="./otherpage.html">Other</a></h4></p>
#github: is\_project\_page:false
google_analytics: G-Z4VDX57ZJ2
theme: minima
  #layout: single
  #classes: wide
#minimal_mistakes_skin: "air"
