theme: jekyll-theme-minimal
title: Camilo Granados
logo: /files/ProfPic3.jpeg
description: Ph.D. Candidate in Economics <br> University of Washington <br> <font size="1"> Email &#58  jcgc [at] uw.edu </font> <p><h3><a href="files/GranadosJC_resume.pdf"> Curriculum Vitae </a></h3></p> <p><h3><a href="files/GranadosJC_resume.pdf">Curriculum Vitae</a></h3></p> <p><a href="files/GranadosJC_resume.pdf">Curriculum Vitae</a></p>

