theme: jekyll-theme-minimal
title: Camilo Granados
logo: /files/ProfPic3.jpeg
description: Ph.D. Candidate in Economics <br> University of Washington <br> <font size="2">  jcgc [at] uw.edu </font> <br> email: <font size="1">   jcgc [at] uw.edu </font> <p><a href="files/GranadosJC_resume.pdf">Curriculum Vitae</a></p>
