theme: jekyll-theme-minimal
title: <h1> Camilo Granados </h1>
logo: /files/MainPicWebsite.JPG
description: Ph.D. candidate in Economics <br> University of Washington <br> <font size="1"> Email &#58  jcgc [at] uw.edu </font> <p><h3><a href="./CV_CGranados.pdf"> Curriculum Vitae </a></h3></p> <p><h3><a href="https://cagranados.github.io/ResearchPage.html">Research</a></h3></p> <p><h5><a href="./teaching.html">Teaching</a></h5></p> <p><h5><a href="./otherpage.html">Other</a></h5></p>
github: is\_project\_page:false
