theme: jekyll-theme-minimal
title: <h1> Camilo Granados </h1>
logo: /files/ProfPic3.jpeg
description: Ph.D. Candidate in Economics <br> University of Washington <br> <font size="1"> Email &#58  jcgc [at] uw.edu </font> <p><h3><a href="files/GranadosJC_resume.pdf"> Curriculum Vitae </a></h3></p> <h3><a href="https://jcamilogranados.github.io/ResearchPage.html">Research</a></h3> <p><a href="files/GranadosJC_resume.pdf">Teaching</a></p> <p><a href="./otherpage.html">Other</a></p>
github:
  is_project_page: false
